project:
  type: website
  output-dir: docs

website:
  title: "gabrielbertolini"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd
      - text: "Conteúdo didático"
        menu:
          - text: "Curso R"
            menu:
              - text: "Aula 1- R Base"
                href: aula_1.qmd
              - text: "Aula 2- Bancos de dados"
                href: aula_2.qmd
              - text: "Aula 3- Gráficos"
                href: aula_3.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



