project:
  type: website
  output-dir: docs

website:
  title: "gabrielbertolini"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd
      - lista.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



