---
title: "About"
---

Doutor em Geociências pela University of Aberdeen e Universidade Federal do Rio Grande do Sul em regime de dupla titulação com período no exterior (Co-tutela) (2015-2020), como bolsista SWE CNPq. Realizou pós-doutorado na UFRGS (2021) como bolsista Capes Print, pós-doutorado na UFRGS (2022) como bolsista Petrobrás e pós-doutorado na UFRGS (2023) como bolsista PRH-14 da ANP. Possui graduação em Geologia pela Universidade do Vale do Rio dos Sinos (UNISINOS) (2010-2014) com período sanduíche na Universidad de Alicante (Espanha) como bolsista CNPq (2012-2013). Possui experiência em técnicas multiproxy (geocronologia U-Pb em zircão detrítico, minerais pesados, sedimentologia aplicada) e em tratamento estatístico aplicado a proveniência sedimentar através de programação. Além disso, tem interesse na caracterização de reservatórios vulcanossedimentares, através de petrofísica, estudos diagenéticos e modelamento geológico. Atualmente, é pesquisador junto ao ITT OCEANEON da Unisinos como bolsista CNPq DTI-B no projeto “Rochas geradoras de hidrocarbonetos na Bacia Sergipe-Alagoas: caracterização multi-proxy, correlação com eventos anóxicos oceânicos (OAEs) e suas implicações na caracterização de sistemas petrolíferos”.