---
title: "Publicações"
editor: visual
---

# Publicações

[Link para download de artigos](https://drive.google.com/drive/folders/1n0zfVX3TVer_l1y-QEPxcdRWpwGcWTbw?usp=sharing)

**BERTOLINI, G.**; HARTLEY, A.J. ; MARQUES, J.C. ; PAIM, J.C. . Controls on grain-size distribution in an ancient sand sea. SEDIMENTOLOGY, v. 71, p. 1, 2023.

SCHERER, CLAITON M.S. ; REIS, ADRIANO D. ; HORN, BRUNO L.D. ; **BERTOLINI, GABRIEL** ; LAVINA, ERNESTO L.C. ; KIFUMBI, CARREL ; GOSO AGUILAR, CESAR . The stratigraphic puzzle of the permo-mesozoic southwestern Gondwana: The Paraná Basin record in geotectonic and palaeoclimatic context. EARTH-SCIENCE REVIEWS, v. 240, p. 104397, 2023.

SCHERER, CLAITON M.S. ; REIS, ADRIANO D. ; HORN, BRUNO L.D. ; **BERTOLINI, GABRIEL** ; LAVINA, ERNESTO L.C. ; KIFUMBI, CARREL ; GOSO, CESAR . Corrigendum to -The stratigraphic puzzle of the permo-mesozoic southwestern Gondwana: The Paraná Basin record in geotectonic and palaeoclimatic context- \[Earth-Science Reviews 240 (2023) 104397\]. EARTH-SCIENCE REVIEWS, v. 243, p. 104505, 2023.

PADILHA, N. L. ; **BERTOLINI, G.** ; MARQUES, J. C. ; GOES, A. M. ; NOGUEIRA, A. C. R. ; MEDEIROS, R. S. P. ; ANDRADE, L. S. ; SODRE, A. A. N. ; CANARIM, D. M. ; SOUZA, P. A. ; SCOMAZZON, A. K. ; OLIVEIRA, E. J. ; SANTOS, J. M. M. . Zircão, o Guardião do Tempo: Datação U-Pb aplicada a provêniencia sedimentar- revisão metodológica e utilidade no projeto Biocronorte. Revista da Academia de Ciências do Piauí, v. 3, p. 157, 2022.

ARAUJO, V. ; MARQUES, J. C. ; **BERTOLINI, G.** ; FRANTZ, J. C. . U-Pb zircon xenocrysts dating as a proxy to assess volcanic assimilation and the underlying crust, Cretaceous Jaguarão Formation, RS-Brazil. Brazilian Journal of Geology, v. 52, p. 1-16, 2022.

João Rodrigo Pilla Dias ; MARQUES, J. C. ; **BERTOLINI, G.** ; FRANTZ, JOSÉ C. ; FRIEDRICH, B. M. ; Carlos José Sobrinho da Silveira ; QUEIROZ, W. ; PAIM, J. C. S. . Regional high-grade metamorphic peak imprint in zircons from the mafic-ultramafic Jacurici Complex, São Francisco Craton, Brazil. BRAZILIAN JOURNAL OF GEOLOGY, v. 52, p. 1-14, 2022.

**BERTOLINI, GABRIEL**; MARQUES, JULIANA ; HARTLEY, ADRIAN J. ; BASEI, M. A. S. ; FRANTZ, JOSÉ C. ; SANTOS, P. R. . DETERMINING SEDIMENT PROVENANCE HISTORY IN A GONDWANAN ERG: BOTUCATU FORMATION, NORTHERN PARANÁ BASIN, BRAZIL. SEDIMENTARY GEOLOGY, p. 105883, 2021.

João Rodrigo Pilla Dias ; **BERTOLINI, G.** ; MARQUES, J. C. ; FRANTZ, J. C. ; Carlos José Sobrinho da Silveira ; CEZARIO, N. . Análise prospectiva de corpos máficos-ultramáficos através de aerogeofísica: Caso de estudo no Vale do Jacurici/Bahia. REVISTA DE GEOCIÊNCIAS DO NORDESTE, v. 7, p. 271-281, 2021.

YU, X. ; WANG, C. ; **BERTOLINI, G.** ; LIU, C. ; WANG, J. . Damp- to dry aeolian systems: Sedimentology, climate forcing, and aeolian accumulation in the Late Cretaceous Liyou Basin, South China. SEDIMENTARY GEOLOGY, v. 426, p. 106030, 2021.

**BERTOLINI, GABRIEL**; MARQUES, JULIANA ; HARTLEY, ADRIAN J. ; DAROSA, ATILA A.S. ; S.SCHERER, CLAITON M. ; BASEI, MIGUEL A.S. ; FRANTZ, JOSÉ C. . Controls on Early Cretaceous desert sediment provenance in south-west Gondwana, Botucatu Formation (Brazil and Uruguay). SEDIMENTOLOGY, p. sed.12715, 2020.

**BERTOLINI, G.**; HARTLEY, A. J. ; MARQUES, J. C. ; HEALY, D. ; FRANTZ, J. C. . The effects of basaltic lava flows on the petrophysical properties and diagenesis of interbedded aeolian sandstones: an example from the Cretaceous Paraná Basin, Brazil. PETROLEUM GEOSCIENCE, p. petgeo2020-036, 2020.
